### ISSUE TITLE
DOI fetching issues: Better user feedback

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref-koppor#220]
I try to fetch a BibTeX for the DOI `10.1007/978-3-319-45348-4_19`, but the console shows

Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://doi.org/10.1007/978-3-319-45348-4_19

An issue of dx.doi.org?

**Comment by koppor** [comment]
Caused by not reachable proxy.

Maybe this should be reported by JabRef. Otherwise, users might get confused.

**Comment by kdaud** [comment]
The error could be indicating that the identified client does not have proper authorization to access to the requested content. On the other hand am tempted to think  that client might be trying to access an invalid URL, the browser could be failing to send the proper credentials to the site. Any thought on this, could this approach enable me reproduce the bug?

**Comment by koppor** [comment]
I think, I had HTTP proxy issues in 2017. Maybe, it as a proxy, where one has to authorize himself and I didn't and if the Web is accessed, 403 is returned.

The idea of the issue is to report the user more detailed information as just "A fetch error occurred" (or similar)

Thus, the logic of fetching entries should be investigated. Maybe, different setups have to be tried. Maybe, it is enough as first idea to also display the HTTP error code and message to the user.

Thus, this is *NOT* a bug, but more a feature request.

**Comment by koppor** [comment]
We improved error reporting; thus I am closing this issue.
